add_requires("glfw", "glad", "assimp", "glm", "stb")
add_requires("imgui", {configs = {glfw = true, opengl3 = true}})

target("opengl")
  set_kind("binary")
  set_languages("cxx20")
  add_files("src/main.cpp")
  add_syslinks("dl", "OpenGL")
  add_packages("glfw", "glad", "assimp", "glm", "stb", "imgui")
  set_rundir("$(projectdir)/")
